// WB04HF123/vue-seed/src/components/Maps/VectorMap.vue
<template>
    <div ref="mapElement" :style="{height: height}"></div>
</template>

<script>
    import $ from 'jquery';
    // jquery Vector Map
    import 'ika.jvectormap/jquery-jvectormap-1.2.2.min.js';
    import 'ika.jvectormap/jquery-jvectormap-world-mill-en.js';
    import 'ika.jvectormap/jquery-jvectormap-us-mill-en.js';
    import 'ika.jvectormap/jquery-jvectormap-1.2.2.css';

    /** Wrapper component for jquery-vectormap plugin */
    export default {
        name: 'VectorMap',
        props: {
            /** series entry of options object */
            series: Object,
            /** markers entry of options object */
            markers: Array,
            /** jvectormap options object */
            options: Object,
            /** height of the container element */
            height: {
                type: String,
                default: '300px'
            }
        },

        mounted() {
            this.options.markers = this.markers;
            this.options.series = this.series;
            $(this.$refs.mapElement).vectorMap(this.options);
        }
    }

</script>

// WB04HF123/reactjs/src/components/Maps/VectorMap.js
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import $ from 'jquery';
// jquery Vector Map
import 'ika.jvectormap/jquery-jvectormap-1.2.2.min.js';
import 'ika.jvectormap/jquery-jvectormap-world-mill-en.js';
import 'ika.jvectormap/jquery-jvectormap-us-mill-en.js';
import 'ika.jvectormap/jquery-jvectormap-1.2.2.css';

/** Wrapper component for jquery-vectormap plugin */
class VectorMap extends Component {

    static propTypes = {
        /** series entry of options object */
        series: PropTypes.object.isRequired,
        /** markers entry of options object */
        markers: PropTypes.array.isRequired,
        /** jvectormap options object */
        options: PropTypes.object.isRequired,
        /** height of the container element */
        height: PropTypes.string
    }

    static defaultProps = {
        height: '300px'
    }

    componentDidMount() {
        this.props.options.markers = this.props.markers;
        this.props.options.series = this.props.series;
        $(this.mapElement).vectorMap(this.props.options);
    }

    setRef = node => this.mapElement = node

    render() {
        return (
            <div ref={this.setRef} style={{height: this.props.height}}/>
        )
    }
}

export default VectorMap;
