// WB04HF123/reactjs/src/components/Charts/ChartRadial.js
import React, { Component } from 'react';
import ContentWrapper from '../Layout/ContentWrapper';
import { Row, Col, Card, CardHeader, CardBody, CardFooter } from 'reactstrap';

import $ from 'jquery';
import * as CONST from '../Common/constants';
import EasyPieChart from 'easy-pie-chart';
// Knob charts
import 'jquery-knob/js/jquery.knob.js';

class ChartRadial extends Component {

    componentDidMount() {

        // Knob
        let knobLoaderOptions1 = {
            width: '50%', // responsive
            displayInput: true,
            fgColor: CONST.APP_COLORS['info']
        };
        $(this.refs.knobChart1).knob(knobLoaderOptions1);

        let knobLoaderOptions2 = {
            width: '50%', // responsive
            displayInput: true,
            fgColor: CONST.APP_COLORS['purple'],
            readOnly: true
        };
        $(this.refs.knobChart2).knob(knobLoaderOptions2);

        let knobLoaderOptions3 = {
            width: '50%', // responsive
            displayInput: true,
            fgColor: CONST.APP_COLORS['info'],
            bgColor: CONST.APP_COLORS['gray'],
            angleOffset: -125,
            angleArc: 250
        };
        $(this.refs.knobChart3).knob(knobLoaderOptions3);

        let knobLoaderOptions4 = {
            width: '50%', // responsive
            displayInput: true,
            fgColor: CONST.APP_COLORS['pink'],
            displayPrevious: true,
            thickness: 0.1,
            lineCap: 'round'
        };
        $(this.refs.knobChart4).knob(knobLoaderOptions4);

        // Easy pie
        let pieOptions1 = {
            animate: {
                duration: 800,
                enabled: true
            },
            barColor: CONST.APP_COLORS['success'],
            trackColor: false,
            scaleColor: false,
            lineWidth: 10,
            lineCap: 'circle'
        };
        new EasyPieChart(this.refs.easypie1, pieOptions1);

        let pieOptions2 = {
            animate: {
                duration: 800,
                enabled: true
            },
            barColor: CONST.APP_COLORS['warning'],
            trackColor: false,
            scaleColor: false,
            lineWidth: 4,
            lineCap: 'circle'
        };
        new EasyPieChart(this.refs.easypie2, pieOptions2);

        let pieOptions3 = {
            animate: {
                duration: 800,
                enabled: true
            },
            barColor: CONST.APP_COLORS['danger'],
            trackColor: false,
            scaleColor: CONST.APP_COLORS['gray'],
            lineWidth: 15,
            lineCap: 'circle'
        };
        new EasyPieChart(this.refs.easypie3, pieOptions3);

        let pieOptions4 = {
            animate: {
                duration: 800,
                enabled: true
            },
            barColor: CONST.APP_COLORS['danger'],
            trackColor: CONST.APP_COLORS['yellow'],
            scaleColor: CONST.APP_COLORS['gray-dark'],
            lineWidth: 15,
            lineCap: 'circle'
        };
        new EasyPieChart(this.refs.easypie4, pieOptions4);
    }

    render() {
        return (
            <ContentWrapper>
                <div className="content-heading">
                    <div>Radial charts
                        <small>Canvas based &amp; No canvas Pure CSS radial progress bars solutions</small>
                    </div>
                </div>
                <h4 className="page-header">Knob</h4>
                <Row>
                    <Col md={ 3 } sm={ 6 }>
                        <Card className="text-center">
                            <CardHeader>Default</CardHeader>
                            <CardBody>
                                <input ref="knobChart1" type="text" defaultValue="80" />
                            </CardBody>
                        </Card>
                    </Col>
                    <Col md={ 3 } sm={ 6 }>
                        <Card className="text-center">
                            <CardHeader>Ready only</CardHeader>
                            <CardBody>
                                <input ref="knobChart2" type="text" defaultValue="45" />
                            </CardBody>
                        </Card>
                    </Col>
                    <Col md={ 3 } sm={ 6 }>
                        <Card className="text-center">
                            <CardHeader>Offset and arc</CardHeader>
                            <CardBody>
                                <input ref="knobChart3" type="text" defaultValue="30" />
                            </CardBody>
                        </Card>
                    </Col>
                    <Col md={ 3 } sm={ 6 }>
                        <Card className="text-center">
                            <CardHeader>Display previous</CardHeader>
                            <CardBody>
                                <input ref="knobChart4" type="text" defaultValue="20" />
                            </CardBody>
                        </Card>
                    </Col>
                </Row>
                <h4 className="page-header">Easypie Charts</h4>
                <Row>
                    <Col md={ 3 } sm={ 6 }>
                        <Card className="text-center">
                            <CardHeader>Default</CardHeader>
                            <CardBody>
                                <div ref="easypie1" data-percent="85" className="easypie-chart">
                                    <span>85</span>
                                </div>
                            </CardBody>
                        </Card>
                    </Col>
                    <Col md={ 3 } sm={ 6 }>
                        <Card className="text-center">
                            <CardHeader>Slim</CardHeader>
                            <CardBody>
                                <div ref="easypie2" data-percent="45" className="easypie-chart">
                                    <span>45</span>
                                </div>
                            </CardBody>
                        </Card>
                    </Col>
                    <Col md={ 3 } sm={ 6 }>
                        <Card className="text-center">
                            <CardHeader>Track color</CardHeader>
                            <CardBody>
                                <div ref="easypie3" data-percent="25" className="easypie-chart">
                                    <span>25</span>
                                </div>
                            </CardBody>
                        </Card>
                    </Col>
                    <Col md={ 3 } sm={ 6 }>
                        <Card className="text-center">
                            <CardHeader>Scale color</CardHeader>
                            <CardBody>
                                <div ref="easypie4" data-percent="60" className="easypie-chart">
                                    <span>60</span>
                                </div>
                            </CardBody>
                        </Card>
                    </Col>
                </Row>
                <h4 className="page-header">Pure CSS
                   <small>radial progress bars solutions</small>
                </h4>
                { /* START row */ }
                <Row>
                    <div className="col-lg-6">
                        { /* START card */ }
                        <Card className="text-center card-default">
                            <CardHeader>Radial Size</CardHeader>
                            <CardBody>
                                <Row>
                                    <Col md={ 3 }>
                                        <div data-label="85%" className="radial-bar radial-bar-85 radial-bar-lg"></div>
                                    </Col>
                                    <Col md={ 3 }>
                                        <div data-label="45%" className="radial-bar radial-bar-45"></div>
                                    </Col>
                                    <Col md={ 3 }>
                                        <div data-label="60%" className="radial-bar radial-bar-60 radial-bar-sm"></div>
                                    </Col>
                                    <Col md={ 3 }>
                                        <div data-label="20%" className="radial-bar radial-bar-20 radial-bar-xs"></div>
                                    </Col>
                                </Row>
                            </CardBody>
                        </Card>
                        { /* END card */ }
                        { /* START card */ }
                        <Card className="text-center card-default">
                            <CardHeader>Radial with Images</CardHeader>
                            <CardBody>
                                <Row>
                                    <Col md={ 3 }>
                                        <div className="radial-bar radial-bar-20 radial-bar radial-bar-danger">
                                            <img src="img/user/03.jpg" alt="Thumbnail" />
                                        </div>
                                    </Col>
                                    <Col md={ 3 }>
                                        <div data-label="35%" className="radial-bar radial-bar-35 radial-bar-warning">
                                            <img src="img/user/01.jpg" alt="Thumbnail" />
                                        </div>
                                    </Col>
                                    <Col md={ 3 }>
                                        <div data-label="50%" className="radial-bar radial-bar-50 radial-bar-info">
                                            <img src="img/user/04.jpg" alt="Thumbnail" />
                                        </div>
                                    </Col>
                                    <Col md={ 3 }>
                                        <div data-label="100%" className="radial-bar radial-bar-100 radial-bar-success">
                                            <img src="img/user/05.jpg" alt="Thumbnail" />
                                        </div>
                                    </Col>
                                </Row>
                            </CardBody>
                        </Card>
                        { /* END card */ }
                        { /* START card */ }
                        <Card className="text-center card-default">
                            <CardHeader>Radial with Tooltips</CardHeader>
                            <CardBody>
                                <Row>
                                    <Col md={ 3 }>
                                        <br/>
                                        <div data-label="85%" data-toggle="tooltip" data-title="85%" className="radial-bar radial-bar-85"></div>
                                    </Col>
                                    <Col md={ 3 }>
                                        <br/>
                                        <div data-label="45%" data-toggle="tooltip" data-title="45%" className="radial-bar radial-bar-45"></div>
                                    </Col>
                                    <Col md={ 3 }>
                                        <br/>
                                        <div data-label="60%" data-toggle="tooltip" data-title="60%" className="radial-bar radial-bar-60"></div>
                                    </Col>
                                    <Col md={ 3 }>
                                        <br/>
                                        <div data-label="20%" data-toggle="tooltip" data-title="20%" className="radial-bar radial-bar-20"></div>
                                    </Col>
                                </Row>
                            </CardBody>
                        </Card>
                        { /* END card */ }
                    </div>
                    <div className="col-lg-6">
                        { /* START card */ }
                        <Card className="text-center card-default">
                            <CardHeader>Radial Variants</CardHeader>
                            <CardBody>
                                <Row>
                                    <Col md={ 3 }>
                                        <div data-label="20%" className="radial-bar radial-bar-20 radial-bar-lg radial-bar-danger"></div>
                                    </Col>
                                    <Col md={ 3 }>
                                        <div data-label="35%" className="radial-bar radial-bar-35 radial-bar-lg radial-bar-warning"></div>
                                    </Col>
                                    <Col md={ 3 }>
                                        <div data-label="50%" className="radial-bar radial-bar-50 radial-bar-lg radial-bar-info"></div>
                                    </Col>
                                    <Col md={ 3 }>
                                        <div data-label="100%" className="radial-bar radial-bar-100 radial-bar-lg radial-bar-success"></div>
                                    </Col>
                                </Row>
                            </CardBody>
                        </Card>
                        { /* END card */ }
                        { /* START card */ }
                        <Card className="card-default">
                            <CardHeader>Radial applications</CardHeader>
                            <CardBody className="text-center">
                                <div data-label="85%" className="radial-bar radial-bar-85 radial-bar-lg"></div>
                                <p>Visitors</p>
                            </CardBody>
                            <CardFooter className="text-center">
                                <Row>
                                    <Col md={ 4 }>
                                        <div data-label="35%" className="radial-bar radial-bar-warning radial-bar-35 radial-bar-sm"></div>
                                        <p>
                                            <small>Conversions</small>
                                        </p>
                                    </Col>
                                    <Col md={ 4 }>
                                        <div data-label="45%" className="radial-bar radial-bar-info radial-bar-45 radial-bar-sm"></div>
                                        <p>
                                            <small>Recurrent</small>
                                        </p>
                                    </Col>
                                    <Col md={ 4 }>
                                        <div data-label="20%" className="radial-bar radial-bar-success radial-bar-20 radial-bar-sm"></div>
                                        <p>
                                            <small>Uniques</small>
                                        </p>
                                    </Col>
                                </Row>
                            </CardFooter>
                        </Card>
                        { /* END card */ }
                    </div>
                </Row>
                { /* END row */ }
            </ContentWrapper>
            );
    }

}

export default ChartRadial;

// WB04HF123/vue/src/views/Charts/ChartRadial.vue
<template>
    <ContentWrapper>
        <div class="content-heading">
            <div>Radial charts
                <small>Canvas based &amp; No canvas Pure CSS radial progress bars solutions</small>
            </div>
        </div>
        <h4 class="page-header">Knob</h4>
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="card">
                    <div class="card-header">Default</div>
                    <div class="card-body text-center">
                        <input ref="knobChart1" type="text" value="80" />
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="card">
                    <div class="card-header">Ready only</div>
                    <div class="card-body text-center">
                        <input ref="knobChart2" type="text" value="45" />
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="card">
                    <div class="card-header">Offset and arc</div>
                    <div class="card-body text-center">
                        <input ref="knobChart3" type="text" value="30" />
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="card">
                    <div class="card-header">Display previous</div>
                    <div class="card-body text-center">
                        <input ref="knobChart4" type="text" value="20" />
                    </div>
                </div>
            </div>
        </div>
        <h4 class="page-header">Easypie Charts</h4>
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="card">
                    <div class="card-header">Default</div>
                    <div class="card-body text-center">
                        <div class="easypie-chart" ref="easypie1" data-percent="85">
                            <span>85</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="card">
                    <div class="card-header">Slim</div>
                    <div class="card-body text-center">
                        <div class="easypie-chart" ref="easypie2" data-percent="45">
                            <span>45</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="card">
                    <div class="card-header">Track color</div>
                    <div class="card-body text-center">
                        <div class="easypie-chart" ref="easypie3" data-percent="25">
                            <span>25</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="card">
                    <div class="card-header">Scale color</div>
                    <div class="card-body text-center">
                        <div class="easypie-chart" ref="easypie4" data-percent="60">
                            <span>60</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <h4 class="page-header">Pure CSS
            <small>radial progress bars solutions</small>
        </h4>
        <!-- START row-->
        <div class="row">
            <div class="col-xl-6">
                <!-- START card-->
                <div class="card card-default">
                    <div class="card-header">Radial Size</div>
                    <div class="card-body text-center">
                        <div class="row">
                            <div class="col-lg-3">
                                <div class="radial-bar radial-bar-85 radial-bar-lg" data-label="85%"></div>
                                <p><code>.radial-bar.radial-bar-85.radial-bar-lg</code></p>
                            </div>
                            <div class="col-lg-3">
                                <div class="radial-bar radial-bar-45" data-label="45%"></div>
                            </div>
                            <div class="col-lg-3">
                                <div class="radial-bar radial-bar-60 radial-bar-sm" data-label="60%"></div>
                            </div>
                            <div class="col-lg-3">
                                <div class="radial-bar radial-bar-20 radial-bar-xs" data-label="20%"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- END card-->
                <!-- START card-->
                <div class="card card-default">
                    <div class="card-header">Radial with Images</div>
                    <div class="card-body text-center">
                        <div class="row">
                            <div class="col-lg-3">
                                <div class="radial-bar radial-bar-20 radial-bar radial-bar-danger">
                                    <img src="img/user/03.jpg" alt="Image" />
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="radial-bar radial-bar-35 radial-bar-warning" data-label="35%">
                                    <img src="img/user/01.jpg" alt="Image" />
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="radial-bar radial-bar-50 radial-bar-info" data-label="50%">
                                    <img src="img/user/04.jpg" alt="Image" />
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="radial-bar radial-bar-100 radial-bar-success" data-label="100%">
                                    <img src="img/user/05.jpg" alt="Image" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- END card-->
                <!-- START card-->
                <div class="card card-default">
                    <div class="card-header">Radial with Tooltips</div>
                    <div class="card-body text-center">
                        <div class="row">
                            <div class="col-lg-3">
                                <br/>
                                <div class="radial-bar radial-bar-85" data-label="85%" data-toggle="tooltip" data-title="85%"></div>
                            </div>
                            <div class="col-lg-3">
                                <br/>
                                <div class="radial-bar radial-bar-45" data-label="45%" data-toggle="tooltip" data-title="45%"></div>
                            </div>
                            <div class="col-lg-3">
                                <br/>
                                <div class="radial-bar radial-bar-60" data-label="60%" data-toggle="tooltip" data-title="60%"></div>
                            </div>
                            <div class="col-lg-3">
                                <br/>
                                <div class="radial-bar radial-bar-20" data-label="20%" data-toggle="tooltip" data-title="20%"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- END card-->
            </div>
            <div class="col-xl-6">
                <!-- START card-->
                <div class="card card-default">
                    <div class="card-header">Radial Variants</div>
                    <div class="card-body text-center">
                        <div class="row">
                            <div class="col-lg-3">
                                <div class="radial-bar radial-bar-20 radial-bar-lg radial-bar-danger" data-label="20%"></div>
                                <p><code>.radial-bar.radial-bar-20.radial-bar-lg.radial-bar-danger</code></p>
                            </div>
                            <div class="col-lg-3">
                                <div class="radial-bar radial-bar-35 radial-bar-lg radial-bar-warning" data-label="35%"></div>
                            </div>
                            <div class="col-lg-3">
                                <div class="radial-bar radial-bar-50 radial-bar-lg radial-bar-info" data-label="50%"></div>
                            </div>
                            <div class="col-lg-3">
                                <div class="radial-bar radial-bar-100 radial-bar-lg radial-bar-success" data-label="100%"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- END card-->
                <!-- START card-->
                <div class="card card-default">
                    <div class="card-header">Radial applications</div>
                    <div class="card-body text-center">
                        <div class="radial-bar radial-bar-85 radial-bar-lg" data-label="85%"></div>
                        <p>Visitors</p>
                    </div>
                    <div class="card-footer text-center">
                        <div class="row">
                            <div class="col-lg-4">
                                <div class="radial-bar radial-bar-warning radial-bar-35 radial-bar-sm" data-label="35%"></div>
                                <p>
                                    <small>Conversions</small>
                                </p>
                            </div>
                            <div class="col-lg-4">
                                <div class="radial-bar radial-bar-info radial-bar-45 radial-bar-sm" data-label="45%"></div>
                                <p>
                                    <small>Recurrent</small>
                                </p>
                            </div>
                            <div class="col-lg-4">
                                <div class="radial-bar radial-bar-success radial-bar-20 radial-bar-sm" data-label="20%"></div>
                                <p>
                                    <small>Uniques</small>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- END card-->
            </div>
        </div>
        <!-- END row-->
    </ContentWrapper>
</template>
<script>

    import EasyPieChart from 'easy-pie-chart';
    import * as CONST from '@/components/Common/Constants';
    // Knob charts
    import 'jquery-knob/js/jquery.knob.js';


    export default {
        data() {
            return {
                // Knob charts
                knobLoaderOptions1: {
                    width: '50%', // responsive
                    displayInput: true,
                    fgColor: CONST.APP_COLORS['info']
                },
                knobLoaderOptions2: {
                    width: '50%', // responsive
                    displayInput: true,
                    fgColor: CONST.APP_COLORS['purple'],
                    readOnly: true
                },
                knobLoaderOptions3: {
                    width: '50%', // responsive
                    displayInput: true,
                    fgColor: CONST.APP_COLORS['info'],
                    bgColor: CONST.APP_COLORS['gray'],
                    angleOffset: -125,
                    angleArc: 250
                },
                knobLoaderOptions4: {
                    width: '50%', // responsive
                    displayInput: true,
                    fgColor: CONST.APP_COLORS['pink'],
                    displayPrevious: true,
                    thickness: 0.1,
                    lineCap: 'round'
                },
                // Easy Pie chart
                pieOptions1: {
                    animate: {
                        duration: 800,
                        enabled: true
                    },
                    barColor: CONST.APP_COLORS['success'],
                    trackColor: false,
                    scaleColor: false,
                    lineWidth: 10,
                    lineCap: 'circle'
                },
                pieOptions2: {
                    animate: {
                        duration: 800,
                        enabled: true
                    },
                    barColor: CONST.APP_COLORS['warning'],
                    trackColor: false,
                    scaleColor: false,
                    lineWidth: 4,
                    lineCap: 'circle'
                },
                pieOptions3: {
                    animate: {
                        duration: 800,
                        enabled: true
                    },
                    barColor: CONST.APP_COLORS['danger'],
                    trackColor: false,
                    scaleColor: CONST.APP_COLORS['gray'],
                    lineWidth: 15,
                    lineCap: 'circle'
                },
                pieOptions4: {
                    animate: {
                        duration: 800,
                        enabled: true
                    },
                    barColor: CONST.APP_COLORS['danger'],
                    trackColor: CONST.APP_COLORS['yellow'],
                    scaleColor: CONST.APP_COLORS['gray-dark'],
                    lineWidth: 15,
                    lineCap: 'circle'
                }
            }
        },
        mounted() {
            // Knob
            $(this.$refs.knobChart1).knob(this.knobLoaderOptions1);
            $(this.$refs.knobChart2).knob(this.knobLoaderOptions2);
            $(this.$refs.knobChart3).knob(this.knobLoaderOptions3);
            $(this.$refs.knobChart4).knob(this.knobLoaderOptions4);
            // Easy pie
            new EasyPieChart(this.$refs.easypie1, this.pieOptions1);
            new EasyPieChart(this.$refs.easypie2, this.pieOptions2);
            new EasyPieChart(this.$refs.easypie3, this.pieOptions3);
            new EasyPieChart(this.$refs.easypie4, this.pieOptions4);
        }
    }

</script>
